name: Publish Crate

on:
  push:
    tags:
      - '*'  # This triggers the action for tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        override-file: rust-toolchain

    - name: Build
      run: cargo build --release

    #- name: Run Tests
    #  run: cargo test --release

    - name: Publish
      run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
