name: test

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: true
      CARGO_INCREMENTAL: 0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools, clippy, rust-src
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-llvm-cov,cargo-nextest
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          just clippy --all-targets
          RUST_BACKTRACE=1 just ci-test
      - name: Upload coverage information
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.75.0
          components: llvm-tools, clippy, rust-src
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Check library code with minimum supported Rust version
        run: |
          just check --lib --locked
